name: deploy-on-server
on:
  push:
    branches:
      - prod
jobs:
  auto-pull:
    name: PullOriginProd
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: git pull origin prod
        working-directory: /home/imustend/www/new-site
