name: deploy-on-server
on:
  push:
    branches:
      - prod
jobs:
  check-bats-version:
    runs-on:
        labels: server
    steps:
      - uses: actions/checkout@v4
      - run: git pull origin prod
        working-directory: /var/www/html/
      
      
